### PR TITLE
Initial Commit to OpenSource Repository

### PR DESCRIPTION
**Pull request by tylerwilding-wk**
Initial Commit to OpenSource Repository

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
The items listed below may not capture all security relevant changes. Before providing a security review, be sure to review the entire PR for security impact.
<details>
<summary>(1) Security relevant changes were detected</summary>
<li>Watched file <code>aviary.yaml</code> added</li>
</details>

## Action Items
* Request infosec review via Slack: #support-infosec
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by aleksandrfurmanov-wk** [comment]
👍

**Review by alexalegre-wf — APPROVED** [review]

**Comment by jeffreymelvin-wf** [comment]
+1 security

**Comment by teresarevious-wf** [comment]
RM +1 dependencies evaluated on tag PR https://github.com/Workiva/barometer/pull/4

**Pull request merged**
